### PR TITLE
First update admin area layout and tooltips

### PR DESCRIPTION
**Pull request by Bopske**
First commit to check that it alle works ok. I will work through the admin area fixing the labels and the tooltips.. so I will add more in here

### CODE REVIEW

**Comment by Bopske** [comment]
@tinoest , this cleans up the layout in the admin pages and it also fixes the tooltips. Feel free to merge it in if this is ok with you...

**Comment by tinoest** [comment]
Thanks, I’ll merge it in and test it. 

That’s a fair few changes.

**Comment by Bopske** [comment]
Yep, the tooltips all needed to be updated to use the Elkarte logic and there were quite a few labels missing.

I deleted my fork from your repository and I now forked the Elk bracnch on TinyPortal. As it seems your latest work is not in there yet, so I will hold of from further testing for now untill you have merged the changes into the development branch here...

**Comment by tinoest** [comment]
I’ve not tested the changes you made but just merged it into the TinyPortal one. I’ll test when I’m back home.

**Pull request merged**
